import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import AuthProvider from "./components/AuthProvider";
import "./globals.css";
import { StoreProvider } from "./redux/storeProvider";

const urbanist = Urbanist({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SlayCanvas",
  description: "Generated by create next app",
  icons: {
    icon: "/Web-Icon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={urbanist.className} style={{ scrollBehavior: "smooth" }}>
        <StoreProvider>
          <AuthProvider>{children}</AuthProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
